<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Don\'t index this page by robots:' => 'Nie indeksuj tej strony przez roboty',
    'Following tag will be added to &lt;head&gt;:<br />&lt;meta name="robots" content="noindex"&gt;' => 'Poniższy tag zostanie dodany do sekcji &lt;head&gt;:<br />&lt;meta name="robots" content="noindex"&gt;',
    'ID' => '',
    'Noindex' => '',
    'Attribute {attribute} is not defined' => 'Atrybut {attribute} nie jest zdefiniowany',
    'Description' => 'Opis',
    'Keywords' => 'Słowa kluczowe',
    'Language' => 'Język',
    'Model' => 'Model',
    'Model ID' => 'Model ID',
    'Open Graph - description' => 'Open Graph - opis',
    'Open Graph - image' => 'Open Graph - obraz',
    'Open Graph - title' => 'Open Graph - tytuł',
    'Open Graph - type' => 'Open Graph - typ',
    'Preferred size for Facebook: {size}' => 'Preferowany rozmiar dla Facebook\'a: {size}',
    'Title' => 'Tytuł',
];
